[build]
publish = "public"
command = "hugo"
[context.production.environment]
HUGO_VERSION = "0.58.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
[context.split1]
command = "hugo --enableGitInfo"
[context.split1.environment]
HUGO_VERSION = "0.58.2"
HUGO_ENV = "production"
[context.deploy-preview]
command = "hugo"
[context.deploy-preview.environment]
HUGO_VERSION = "0.58.2"
[context.branch-deploy]
command = "hugo"
[context.branch-deploy.environment]
HUGO_VERSION = "0.58.2"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"